GET http://localhost:4004/catalog/Phones/1

###
PATCH http://localhost:4004/catalog/Phones/1
Content-Type: application/json

{
    "stock": 1000
}

###
POST http://localhost:4004/catalog/Orders
Content-Type: application/json

{
    "phone_ID": 4, "amount": 22
}

###
POST http://localhost:4004/catalog/Phones
Content-Type: application/json

{
    "ID": 61,
    "title": "test",
    "producer_ID": 1001,
    "price": 200,
    "stock": 321355,
    "imageUrl": "content2.onli/catalog/device/main/7"
}